### ISSUE TITLE
애니메이션 추가하기

### ISSUE THREAD

**Issue by dl0312** [h3s1/youtopia_client#24]
## ✨ What?
앱에 좀 더 심리스한 경험을 주기위해 애니메이션을 추가합니다.

## 🛠 How?
airbnb의 lottie를 이용합니다.

## 📚 Reference
* [airbnb-lottie](https://airbnb.design/introducing-lottie/)
* [lotttie-react-native](https://github.com/react-native-community/lottie-react-native)

**Comment by chaewonkong** [comment]
로티 좋아욤
